/-
Copyright (c) 2026 Barinder S. Banwait. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Barinder S. Banwait
-/

import Mathlib.Algebra.QuadraticAlgebra.Basic
import Mathlib.RingTheory.Adjoin.Basic
import RamanujanNagell.QuadraticIntegers.RingOfIntegers

open QuadraticAlgebra

noncomputable section

/-! ## The field isomorphism K' ≃ₐ[ℚ] K

We construct an explicit ℚ-algebra isomorphism between
  K' = QuadraticAlgebra ℚ (-7) 0   (ω' satisfies (ω')² = -7)
  K  = QuadraticAlgebra ℚ (-2) 1   (ω  satisfies ω²  = -2 + ω)

The isomorphism sends ω' ↦ 2ω - 1 (in K), since:
  (2ω - 1)² = 4ω² - 4ω + 1 = 4(-2 + ω) - 4ω + 1 = -8 + 4ω - 4ω + 1 = -7  ✓

The inverse sends ω ↦ (ω' + 1)/2 (in K').
-/

-- Use a local abbreviation to avoid exporting `K` into the importer's namespace.
-- Callers should use `QuadraticAlgebra ℚ (-2 : ℤ) 1` directly.
private abbrev Klocal := QuadraticAlgebra ℚ (-2 : ℤ) 1

/-- The ℚ-algebra map K' → K sending ω' ↦ 2ω - 1. -/
def toK : K' →ₐ[ℚ] Klocal :=
  QuadraticAlgebra.lift ⟨2 * (ω : Klocal) - 1, by
    -- Need: (2ω-1)² = (-7:ℚ)•1 + 0•(2ω-1)  in Klocal
    -- Verified component-wise: .re = 1 - 8 = -7, .im = -2 - 2 + 4 = 0
    ext
    · simp [re_mul, im_mul, omega_re, omega_im]; ring
    · simp [re_mul, im_mul, omega_re, omega_im]; ring⟩

/-- The ℚ-algebra map K → K' sending ω ↦ (ω' + 1)/2. -/
def toK' : Klocal →ₐ[ℚ] K' :=
  QuadraticAlgebra.lift ⟨(1/2 : ℚ) • ((ω : K') + 1), by
    -- Need: ((ω'+1)/2)² = (-2:ℚ)•1 + 1•((ω'+1)/2)  in K'
    -- LHS: (-7+2ω'+1)/4 = -3/2 + ω'/2 = -2 + (ω'+1)/2 = RHS  ✓
    ext
    · simp [re_mul, im_mul, omega_re, omega_im, re_smul, im_smul]; ring
    · simp [re_mul, im_mul, omega_re, omega_im, re_smul, im_smul]; ring⟩

/-- The field isomorphism K' ≃ₐ[ℚ] K. -/
def fieldIso : K' ≃ₐ[ℚ] Klocal :=
  AlgEquiv.ofAlgHom toK toK'
    (QuadraticAlgebra.algHom_ext (by
      simp only [AlgHom.comp_apply, AlgHom.id_apply]
      simp [toK, toK', lift, omega_re, omega_im, re_smul, im_smul, smul_add, smul_smul]
      ext
      · simp [re_smul, re_mul, omega_re, omega_im]
      · simp [im_smul, im_mul, omega_re, omega_im, smul_eq_mul]))
    (QuadraticAlgebra.algHom_ext (by
      simp only [AlgHom.comp_apply, AlgHom.id_apply]
      simp [toK, toK', lift, omega_re, omega_im, re_smul, im_smul, smul_add, smul_smul]))

/-- The isomorphism sends ω' to 2ω - 1. -/
lemma fieldIso_omega : fieldIso (ω : K') = 2 * (ω : Klocal) - 1 := by
  simp [fieldIso, toK, lift]

/-- Every element of `QuadraticAlgebra ℤ a b` is generated by `ω` as a ℤ-algebra. -/
lemma quadraticAlgebra_adjoin_omega_eq_top (a b : ℤ) :
    Algebra.adjoin ℤ ({ω} : Set (QuadraticAlgebra ℤ a b)) = ⊤ := by
  rw [Algebra.eq_top_iff]
  intro x
  have hx : x = algebraMap ℤ _ x.re + x.im • ω := by
    apply QuadraticAlgebra.ext <;> simp
  rw [hx]
  exact Subalgebra.add_mem _
    (Subalgebra.algebraMap_mem _ _)
    (Subalgebra.smul_mem _ (Algebra.self_mem_adjoin_singleton ℤ ω) _)

end
